### ISSUE TITLE
Combobox's clear 'X' button is inset too far

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro-combobox#121] opened 2023-02-13 23:59 UTC
## Describe the bug

When comparing the location of the X to clear the combobox field with other input elements, it is too far inset from the right. Does not match design specs and wastes input space.

## To Reproduce

Hover over a combobox on auro doc site or at alaskaair.com/search.

## Expected behavior

The location of the X should match datepicker and other input fields and be more symmetrical on left/right sides, matching design specs.

## Screenshots

Not symmetrical/Wasted space on right side of field:
![image](https://user-images.githubusercontent.com/34354487/218601352-5445ab86-cf14-404f-93e5-ed544ac8ced3.png)

![image](https://user-images.githubusercontent.com/34354487/218601825-87ff622d-d0bf-4a65-8c8d-bc8c1fbce3e2.png)

Correct/Symmetrical:
![image](https://user-images.githubusercontent.com/34354487/218601124-cc5e4794-6191-4d7d-a737-72395499bdea.png)

**Comment by blackfalcon** [comment] 2023-02-23 00:21
This issue is validated. See the screen shot below, the additional spacing is caused by an incorrect CSS value. 

<img width="655" alt="Screen Shot 2023-02-22 at 4 21 01 PM" src="https://user-images.githubusercontent.com/181089/220794082-ef08b624-0cae-4683-974c-17c721d90488.png">

**Comment by blackfalcon** [comment] 2023-02-23 00:23
## Work specification 

Remove the unnecessary right spacing. 

## Exit criteria 

Validate that the padding is consistent with the design spec and that there are no unintended side-effects from removing this value.

**Comment by jason-capsule42** [comment] 2024-03-06 04:53
I have verified that this issue was previously fixed by updates to the auro-input component and how it's implemented into auro-combobox. Closing this issue as already fixed.

**Closed by jason-capsule42** 2024-03-06 04:53 UTC
Labels: not-reviewed, Type: Bug, auro-combobox
