### ISSUE TITLE
Missing arrow and weird blue box

### ISSUE THREAD

**Issue by braven112** [AlaskaAirlines/auro-combobox#187] opened 2024-09-10 16:42 UTC
### Please verify the version of auro-combobox you have installed

@latest

### Please describe the bug

Go to Auro docsite
Go to auro-combobox
See dropdown arrow is blue and arrow seems to be located outside of the component.

![image](https://github.com/user-attachments/assets/88ea1c0e-1ccb-4e8f-b1f0-db4d221b56e8)

### Reproducing the error

This issue is reproducible on the Auro docsite

### Expected behavior

I would expect an arrow like select

### What browsers are you seeing the problem on?

Chrome

### Additional context

I only checked one browser.

### Exit criteria

Arrow design matches blueprint.

**Comment by Patrick-Daly-AA** [comment] 2024-09-11 20:02
Root cause of bug is an issue in Auro input that'll be going out shortly.  moving to code review needed to await re-test after that fix is in.

**Closed** 2024-10-04 19:45 UTC
Labels: auro-combobox
