### ISSUE TITLE
Checkmark is not applied on select

### ISSUE THREAD

**Issue by chrisfalaska** [AlaskaAirlines/auro-combobox#204] opened 2024-11-14 19:36 UTC
### Please verify the version of auro-combobox you have installed

2.1.4

### Please describe the bug

1. Go to the [DocSite](https://auro.alaskaair.com/components/auro/combobox#gsc.tab=0)
2. Interact with the "Example with checkmark for selected option"
3. Type "Apple"
4. Click on "Apple" from dropdown
5. Note that checkmark is not applied

https://github.com/user-attachments/assets/9dc10fad-b9ba-4be0-af3f-ae35a1188cc3

### Expected behavior

The checkmark should be applied when selected to indicate the option has been chosen.

**Comment by jason-capsule42** [comment] 2024-11-15 20:31
This is a duplicate of #184

**Closed by jason-capsule42** 2024-11-15 20:31 UTC
Labels: auro-combobox
